# action.yml
name: "Conventional Commit"
description: "Validate PR title according to conventional commit spec"
# runs:
#   using: "docker"
#   image: "docker://ghcr.io/lab42/conventional-commit:latest"

runs:
  using: "composite"
  steps:
    - run: install.sh
      shell: bash
    - run: conventional-commit
      shell: bash
