name: Pull request

on:
  pull_request: {}

permissions:
  pull-requests: read

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: lab42/conventional-commit@main
