name: Pull request

on:
  pull_request: {}

jobs:
  Validate:
    runs-on: [self-hosted]
    steps:
      - name: Validate PR title
        uses: lab42/conventional-commit@main
        with:
          description_regexp: (.*)
